<?php

namespace Adoptez\AnimalsBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{

    public function getAdvertsInCategories(array $categoryID){
        /*$qb = $this
            ->createQueryBuilder('a')
            ->leftJoin('a.categorie', 'cat')
            ->addSelect('cat');

        $qb->where($qb->expr()->in('cat.id', $categoryID));*/
    }
}
