# src/Adoptez/AnimalesBundle/Resources/config/routing.yml

# homepage
adoptez_animals_home:
    path:     /
    defaults: { _controller: AdoptezAnimalsBundle:Advert:index }

# animals listing
adoptez_animals_list:
    path:      /{place}/{animal}/{page}
    defaults:
        _controller: AdoptezAnimalsBundle:Advert:listing
        place: "france"
        animal: "tous"
        page: 1
    requirements:
        page: \d*

# animal view
adoptez_animals_view:
    path:      /{place}/{animal}/{idName}
    defaults:  { _controller: AdoptezAnimalsBundle:Advert:view }

# add animal
adoptez_animals_add:
    path:      /ajouter
    defaults:  { _controller: AdoptezAnimalsBundle:Advert:add }

# edit animal
adoptez_animals_edit:
    path:      /modifier/{id}
    defaults:  { _controller: AdoptezAnimalsBundle:Advert:edit }
    requirements:
        id: \d+

# delete animal adopted
adoptez_animals_adopt:
    path:      /supprimer/{id}
    defaults:  { _controller: AdoptezAnimalsBundle:Advert:adopt }
    requirements:
        id: \d+